### ISSUE TITLE
entity not showing like chest when installed on client side

### ISSUE THREAD

**Issue by VirtualGaming1** [yurisuika/Compost#1]
So I just installed your mod in my modpack but when i load it on the client side notice I can't see my chest i placed also the cant see item that is dropped.

without mod on client
![image](https://user-images.githubusercontent.com/20447403/180744596-a82113d4-0c4d-490e-938f-1650b4d35ae2.png)
![image](https://user-images.githubusercontent.com/20447403/180744801-f71916aa-d1f9-4188-a117-a79fc93a50f7.png)
![image](https://user-images.githubusercontent.com/20447403/180744841-5d647541-934b-4cd2-a3a5-1836af5aa48d.png)

with mod on client
UMMMMM
OK as I was doing this I just re-enabled the mod and not it works betting. Im going to test it more but strange though

**Comment by yurisuika** [comment]
This mod should have nothing to do with your issue; I'd look into your other mods. It only changes what item is dropped by the composter.
