### ISSUE TITLE
non-English world name cause crash

### ISSUE THREAD

**Issue by QLNPLUS** [yurisuika/Compost#12]
I have a problem in using this mod. This mod may cause garbled text when automatically reading the saved config file if the save file name contains non-English characters (such as Chinese). The game may crash upon the next launch.

**Comment by yurisuika** [comment]
I cannot replicate. Can you provide further details?

![image](https://github.com/user-attachments/assets/a28ee66c-01c2-4573-916e-257000f67105)
![image](https://github.com/user-attachments/assets/99f753f0-d2c8-424e-b1fd-34fef404a860)

Unless you are talking about the config's actual filename. But that should always be `compost.json`. I don't know how you would have managed to alter that without modifying the mod.

**Comment by yurisuika** [comment]
We've been discussing this on Discord, but if anyone else comes across this, it seems to only be present in 1.20.4 and older. This means it is pre-Java 21, but also concerns Gson moving from 2.10 to 2.10.1 (what we use to parse JSON for the config). This is a built-in library with Minecraft.

As far as that goes, those are my only leads at the moment.

**Comment by yurisuika** [comment]
Problem solved, Java 17 uses `windows-1252` as a default charset. J21 uses UTF-8, so it is just a matter of setting Filewriter to use UTF-8. For making older versions functional, a solution to this would be running MC with J21.
