### ISSUE TITLE
Question regarding Interactions between mod Upcycle (2.0.0) and Compost (1.4.0) in 1.21.1 (NeoForge 21.1.65)

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [yurisuika/Compost#14]
Hi again, I'm not exactly sure if I should be asking this question here or in Upcycles issues page.

Upcycle adds on more items to be composted from vanilla minecraft such as rotten flesh, spider eyes and glistering melon to name a few. Something that normal minecraft doesn't compost. Would that mods modification of the composters ability to compost more items conflict with your mods modification of the composters ability to get more items, specified in your mods config, out of the composter itself?

**Comment by yurisuika** [comment]
It extends the vanilla composter so it inherits the compostables map. It shouldn't conflict in that regard.

**Comment by DatrixTheHybridShadowWolf** [comment]
Hmmm...strange...Thanks for the response.
