### ISSUE TITLE
Please addd EMI integration

### ISSUE THREAD

**Issue by MrRedstoneToGo** [yurisuika/Compost#6]
EMI still shows bone meal as an composting output even if the first item stack in the config is set to another item.

**Comment by yurisuika** [comment]
![2024-04-27_18 18 32](https://github.com/yurisuika/Compost/assets/7410303/6bf5a082-649f-40c2-b094-e54f52feb1ba)

This should be satisfactory... the vanilla plugin's bone meal recipes have been removed like I've done in REI through a mixin, and added our own plugin.

The outputs cycle through and will have one of their possible counts added. The "x7" text has been removed, as such.

**Comment by yurisuika** [comment]
Actually I've realised the "x7" is referring to the amount of composting levels, not the amount of bone meal. I've un-removed that.

**Comment by yurisuika** [comment]
Even better, I nixed the plugin and just did it directly as a mixin.
https://github.com/yurisuika/Compost/actions/runs/8864384656

**Comment by MrRedstoneToGo** [comment]
When will there be a new update on Modrinth and CurseForge to make these changes "official"? I've been waiting for this for so long.

**Comment by yurisuika** [comment]
It should be out within a week. I've made a lot of changes to the mod since, including a complete remapping to mojmap.

There is one hanging issue in that EMI and REI do not have releases for Forge 50+ and ArchLoom cannot assemble because of mapping conflicts with using older mod versions to build off of, so Forge support may be dropped for now for 1.20.5+.

**Comment by MrRedstoneToGo** [comment]
I almost always use fabric. Also, REI is only available for fabric, and I think EMI was originally a fabric mod as well, but most forge users use JEI anyway, so this issue shouldn't be that important.
Thanks for your answer!
I'm afraid of the other features in the new update.

**Comment by yurisuika** [comment]
Alright well good news is that I found that ArchLoom has a PR that fixes the mapping conflicts, so using that I'll be able to keep support in for both mods, though who knows once they come out for it if they will work (since it requires mixing into them, unstable way of adding support).

**Comment by MrRedstoneToGo** [comment]
Is there a way to set the output of the composter in every world in a Minecraft instance to the same items (no commands)? My pre-update config didn't work anymore ... but it showed the right items in EMI.

**Comment by yurisuika** [comment]
no, but that is a good idea for a feature

**Comment by MrRedstoneToGo** [comment]
That was the case before...

**Comment by MrRedstoneToGo** [comment]
That was already a feature in the previous version...
