### ISSUE TITLE
Crash with REI (Forge)

### ISSUE THREAD

**Issue by MrRedstoneToGo** [yurisuika/Compost#7]
Every time I load REI (12.0.684) and Compost (1.3.0) on Forge the game crashes (Yes, I have architectury (9.2.14) and cloth-config (11.1.118) installed):
[latest.log](https://github.com/yurisuika/Compost/files/14623211/latest.log)

[crash-2024-03-16_11.20.22-fml.txt](https://github.com/yurisuika/Compost/files/14623210/crash-2024-03-16_11.20.22-fml.txt)

**Comment by yurisuika** [comment]
Whoops, I accidentally made the plugin class abstract for this version when I was making all my mixin classes abstract. Fixed.
