### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DatrixTheHybridShadowWolf** [yurisuika/Compost#9]
Would this work with 1.20.6? I haven't seen anything updated for this mod since 7 months ago and was just wondering. I like this mod a lot. I'd hate to see it stuck.

**Comment by yurisuika** [comment]
I've been working on a big update over the past several months and it is near release.

**Comment by DatrixTheHybridShadowWolf** [comment]
Thanks for the response I appreciate that. I'll be waiting for it then.
